### ISSUE TITLE
SQL-like-operations-in-Pandas

### ISSUE THREAD

**Issue by Maryam0330** [Munsif-Raza-T/Artificial-Intelligence-and-Data-Science#6]
I am writing to propose a contribution to the pandas data analysis project. I have developed a set of SQL-like operations that can be used to manipulate data in pandas DataFrames. These operations are similar to the operations that are available in SQL, but they are designed to be more efficient and easier to use.
I believe that these operations would be a valuable addition to the pandas project. They would make it easier for users to perform complex data analysis tasks, and they would improve the performance of pandas.

**Comment by Munsif-Raza-T** [comment]
Yes you can go for it

**Comment by Maryam0330** [comment]
Okay! Thank you
